### ISSUE TITLE
Consider taking donations in Bitcoin

### ISSUE THREAD

**Issue by morrisonbrett** [sdegutis/mjolnir#127]
Why just PayPal?  Add a Bitcoin wallet address to your Donation ask.  :-)

**Comment by sdegutis** [comment]
@morrisonbrett I'm not smart enough to know how to get a Bitcoin wallet. Or how Bitcoin works. :(

**Comment by sdegutis** [comment]
@morrisonbrett Well, if you want to donate through Bitcoin, then I will look into what it takes to accept such donations :)

**Comment by sdegutis** [comment]
@morrisonbrett from what I understand, a Bitcoin address can only receive Bitcoins once due to privacy and security concerns, making it unsuitable for pasting on the readme page next to the Paypal donation link; I'm probably going to sign up for bitpay.com which I've heard is a reliable higher-level way to receive bitcoins

**Comment by sdegutis** [comment]
In that case, I just installed Electrum and setup a new wallet; I now have a 34-character address that I believe btc can be sent to :)

**Comment by sdegutis** [comment]
@colindean I'm not sure I feel comfortable accepting recurring donations; that seems like it's more appropriate for long-term funding/sponsoring of a project, and I can't imagine anyone would want to do that for Hydra.

**Comment by sdegutis** [comment]
Going to add this to the README in a second:

> Bitcoin donations: 18LEhURYNgkC9PPdtdXShDoyaHXGaLENe7

**Comment by sdegutis** [comment]
@colindean You've convinced me: https://www.gittip.com/sdegutis/

**Comment by sdegutis** [comment]
@morrisonbrett :cake:
