### ISSUE TITLE
Make it work with OS X 10.8

### ISSUE THREAD

**Issue by bradparks** [sdegutis/mjolnir#156]
Hey! This looks super cool - is there any reason it can't target 10.8? I installed via cask and using the downloadable release, and both are a binary that only supports 10.9.

If I built it from source would that be able to target 10.8 ?

**Comment by sdegutis** [comment]
@bradparks It uses a few 10.9-specific APIs.

**Comment by sdegutis** [comment]
Hmm, dunno. Let me try to compile for 10.8 and see.

**Comment by sdegutis** [comment]
It looks like it's just `hydra_check_accessibility()` that fails to compile on 10.8... I certainly don't mind trying to get the 10.8 solution to work in its place, as long as it's not super ugly and confusing. That said, this is the only thing that fails to compile; not sure what other APIs we use that work differently on 10.9, but Apple's usually good about API compatibility, so that shouldn't be a problem.

**Comment by sdegutis** [comment]
@bradparks it should work, it's just a matter of testing it on OS X 10.8 (which I don't have)

**Comment by sdegutis** [comment]
Pretty sure it's in the Phoenix issues somewhere. Or at least in the Phoenix git history. So that should do the trick. The only hard part is linking on 10.8 with a NULL new function instead of not being able to link at all.

**Comment by sdegutis** [comment]
This is pretty much done, as long as someone can get e380b8cd5d6297217a4c5256e8b403343d0502ec to link -- I'm lost.

**Comment by sdegutis** [comment]
@bradparks that seemed to make it work -- can you build off master and try it out, if you have Xcode installed?

**Comment by sdegutis** [comment]
@bradparks Awesome. Sounds like this feature is done to me :)
