### ISSUE TITLE
Make transient bookkeeping arrays private

### ISSUE THREAD

**Issue by muescha** [sdegutis/mjolnir#158]
bind - create hotkey - store in keys
unbind - delete hotkey - remove from keys

enable - activate hotkey - leave in keys
disable - deactivate hotkey - leave in keys

just now a hotkey is deleted from hotkey.keys
for an enableall then there is no reference for it. 

or 

store it in an hotkey.disabledkeys

**Comment by sdegutis** [comment]
I'm not sure about this. The primary purpose of `hotkey.keys` is for Hydra to use for bookkeeping, mainly so that `hydra.reload()` is able to completely unregister all hotkeys. It's only incidentally useful for giving users access to all (registered, but that's in dispute) hotkeys.

Perhaps `hotkey.keys` should be made private, and if users want some kind of bookkeeping then they can create their own table and add them to it? That seems like the cleanest solution.

**Comment by sdegutis** [comment]
The solution for this is to make all such bookkeeping arrays private, such as for timers, pathwatchers, textgrids, etc.

**Comment by sdegutis** [comment]
Apparently I already did this at some point. Woot. Done.

**Comment by sdegutis** [comment]
@asmagill Modules included from `ext` should never bind hotkeys for you. They should only provide functions that you can bind in your own `init.lua`.

**Comment by sdegutis** [comment]
@asmagill In my experience, bad modules quickly die from lack of use and are avoided by word of mouth, i.e. survival of the fittest. Also, we can't tell whether a hotkey is already bound via something else outside of our program, as far as I can know. You're welcome to override `hotkey:enable` in your own configs to add this check, but as long as everyone plays nicely and follows existing conventions and guidelines, the check would be unnecessary.

**Comment by sdegutis** [comment]
@asmagill 

``` lua
local realbind = hotkey.bind
function hotkey.bind(mods, key, pressedfn, releasedfn)
    local k = realbind(mods, key, pressedfn, releasedfn)
    -- do moar things; maybe check `mods` and `key` or something
    return k
end
```
