### ISSUE TITLE
Should Lua be vendored like it is?

### ISSUE THREAD

**Issue by colindean** [sdegutis/mjolnir#22]
I found [this framework bundle](https://github.com/derkyjadex/Lua-Framework) that might be a more idomatic way to ship it.

**Comment by sdegutis** [comment]
Oh hey good idea.

**Comment by sdegutis** [comment]
Part of the reason I threw the source code in was because I have had headaches in days-past caused by PPC and Intel and 32-bit and 64-bit compilations. It got really ugly and I didn't want to mess with yak shaving when I threw this together.

But now that the app actually compiles, is there any real, tangible benefit to switching to using Lua.framework instead of just continuing on as we do now?

**Comment by sdegutis** [comment]
@colindean We use Clojure and Ruby at work, and I do love the dead-simple dependency management that Leiningen and Bundler give me. I haven't really gotten into CocoaPods yet, since I started doing Mac apps about 5 years ago before it came out. Back then, the simplest way was to throw the source code right into your project. It still is the simplest way actually, although it's definitely got some drawbacks. But I think the pros outweigh the cons in this situation. We don't have such a large dependency tree that makes it worth using a third party system. Lua stands on its own. And when we need to upgrade Lua, it would be pretty easy. So at this point I don't see much benefit to using CocoaPods or Lua.framework or even building `liblia.a` and statically linking against that.

**Comment by sdegutis** [comment]
Also yeah, I looked into the ObjC Lua bridge(s). It tries to be like PyObjC and RubyCocoa (not MacRuby or Nu). It's definitely not worthwhile, for the same reasons that PyObjC and RubyCocoa were (semi?)retired.
