### ISSUE TITLE
Settings (init.lau) located in ~/Library/Application Support/Hydra

### ISSUE THREAD

**Issue by bglnelissen** [sdegutis/mjolnir#223]
I have a feature request for the storage location of settings and 'plugins'.

One of my favorites of BBedit is that it looks for its settings folder in hierarchal order: 
~/Dropbox/Application Support/BBEdit
~/Library/Application Support/BBEdit

Once found, thats the folder to use. This makes it really easy to have the same settings on multiple machines. Although this can be achieved using symlinks and dropbox, the BBedit way is much cleaner. [BBedit explanation](http://www.barebones.com/products/bbedit/bbedit10.html)

**Comment by sdegutis** [comment]
@bglnelissen What settings and plugins in particular would go here?

**Comment by sdegutis** [comment]
@bglnelissen I used to store this kinda stuff in Dropbox, but it causes a ton of disk activity, plus it really messes up the permissions of my files, which is super annoying. Now I just store it in a git repo instead, and keep it in sync between my computers via github. If you don't have a dotfiles repo, you could just have `~/.hydra/` be a github repo by itself. But overall I'm against making Dropbox easier for this kind of thing partly because it's trivial to use symlinks, and partly because I'm still not fully sure I've fixed all my file permissions in my projects (recursively!) from those few months I had them in Dropbox, and I would hate to inflict that same fate upon anyone else.
