### ISSUE TITLE
Add {cut, copy, paste} support

### ISSUE THREAD

**Issue by af** [sdegutis/mjolnir#238]
One old zephyros feature that hydra lacks is access to the system clipboard. Would this be a possible addition for hydra?

**Comment by sdegutis** [comment]
Probably.

**Comment by sdegutis** [comment]
@af I just looked at the way the "copy" feature worked in Zephyros:
1. Sent a fake key-press of "Cmd-C"; this will be available when the `eventtap` module is done
2. Slept for 1/8 of a second
3. Looked for contents of clipboard as a string
4. If found, return it; otherwise, start at step 2 again; repeat maximum of 10 times
5. If still not found, return ""

This seems like not the best solution. But anyway, you should be able to fake "Cmd-C" and "Cmd-V" and "Cmd-X" in Lua when the `eventtap` module is done, which is most of the work. The polling you can also do in Lua. I'll also add a `pasteboard` module with a method `string` and maybe some more methods too. Then this entire feature will be doable in Lua, and should probably become a new module under `ext`.
