### ISSUE TITLE
window output init.lua line 6 unexpected < doing nothing.

### ISSUE THREAD

**Issue by zinking** [sdegutis/mjolnir#243]
I am using https://github.com/sdegutis/dotfiles/blob/osx/home/.hydra/init.lua this config (with the 'grid' sample config ) on my maveric, but when I click loadconfig, following errors pop up 
`window output init.lua line 6 unexpected < doing nothing`
1. firstly no idea where is the log located, can only show the splash screen displaying this. thus I cannot get the detailed exception for you. 
2. I am using mac os maverick and latest hydra latest sample from the links.

**Comment by sdegutis** [comment]
@zinking I really don't understand what problem you're seeing.

**Comment by sdegutis** [comment]
@zinking Can you give more info on this?

**Comment by sdegutis** [comment]
@zinking Thanks for the extra info. I'm not sure why you're getting that error. Maybe there is a typo somewhere in the copied config file. Otherwise, all I can suggest is starting with the sample_init.lua that Hydra comes with. (Delete your own init.lua and start Hydra and open the menu to see it.)

**Comment by sdegutis** [comment]
@zinking The point of Hydra is that you can build your own config, and since I figured that people might like the grid functionality, I packaged it up in a convenience API as `ext.grid` so that you can bind grid functions to hotkeys in your own config. Using someone else's config is not really the ideal way to get started, since you'll run into errors and not know how to fix them. You should start off writing your own config line by line so you can get the hang of Hydra's API.
