### ISSUE TITLE
Can pathwatcher support glob?

### ISSUE THREAD

**Issue by bolasblack** [sdegutis/mjolnir#271]
I want hydra auto reload config files, so I add this in `init.lua`:

``` lua
pathwatcher.new(CONFIG_PATH, hydra.reload):start()
```

It works well.

But when I open `init.lua` by vim, it auto reloaded because of the new file named`.init.lua.swp`.

So I hope `pathwatcher` can support glob, then I can write like this:

``` lua
pathwatcher.new(os.getenv("HOME") .. "/.hydra/*.lua", hydra.reload):start()
```

**Comment by sdegutis** [comment]
@bolasblack There's two ways to do this: the first is to glob out an actual list of files, and watch them independently; you can technical do this right now, but you'd need one pathwatcher for each file, since they can only watch one file (for the time being); the second way is to change the pathwatcher handler to return the changed files; I'm not sure if this is possible, but it would certainly be more flexible than the first way.

**Comment by sdegutis** [comment]
@jhgg That's a good plan. You can do it if you want, but I was planning on doing this, but haven't gotten to it. So instead you might want to do something I'm not qualified to do, like #268 and #116 (I tried the private APIs for spaces, too hard for me to figure out) :laughing: 
@bolasblack Yep.

**Comment by sdegutis** [comment]
I've seen how [osxmonad](https://github.com/xmonad/osxmonad/) does it. And I thought I tried the same APIs here. But they didn't do anything. Maybe I just used it wrong. After all, I don't know any Haskell, so I only read the C parts of the code, and might have missed something.

**Comment by sdegutis** [comment]
(Sorry, that comment was about spaces, not pathwatcher; moving discussion to #116).
