### ISSUE TITLE
Not clear that disabling/reenabling accessibility is required when installing/upgrading

### ISSUE THREAD

**Issue by 4tXJ7f** [sdegutis/mjolnir#272]
When using the sample configuration, I get the following error:

```
Error: /Users/XXX/.hydra/init.lua:37: attempt to index local 'win' (a nil value)
```

when selecting a window and pressing cmd+ctrl+alt+L.
I did not change the sample configuration at all.
Executing `movewindow_righthalf()` in the REPL works without an error.

**Comment by sdegutis** [comment]
@4tXJ7f This usually means accessibility isn't enabled for Hydra.

**Comment by sdegutis** [comment]
@4tXJ7f You shouldn't need to reboot, just disable and re-enable accessibility for Hydra. That should do it.

**Comment by sdegutis** [comment]
@4tXJ7f Did you look anywhere for this before coming here to file an issue? This is a frequently asked question, having the same solution every time, so I'd like to put it somewhere that's commonly checked.

**Comment by sdegutis** [comment]
@4tXJ7f Thanks for the feedback. There already is an alert that says that, but either it's not showing up, or it's not prominent enough. I'll change it to an alert instead of a user notification, and put an item in the FAQ for this.
- [x] change accessibility warning to alert
- [x] put item about this in FAQ
- [x] put explicit reminder in upgrade notes (changelog)
