### ISSUE TITLE
Keyboard Driven Exposé

### ISSUE THREAD

**Issue by andrewhampton** [sdegutis/mjolnir#508]
This is on my "TODO Eventually" list, but if someone wants to do it sooner, please feel free! :)

What I have in mind is a keyboard driven version of Exposé. Here's how it would work

1) Hit keybinding
2) All windows are resized and arranged so that they are visible
3) Each window would get an overlay with a number on it
4) Typing that number would put all windows back to their original position and size, but with the matching window focused

Note, if there are more than 10 windows, so if you had 15 windows open, you would have one window with 1 and another window with 12 on the overlay. I would like step 4 to happen as soon as possible, so in this scenario, typing "2" would immediately focus the appropriate window, but typing "1" would waiting for the next key. "Enter" would then focus window 1, but "3" as the next key would immediately focus window 13.

**Comment by muescha** [comment]
If its more then 9 windows the overlay count starts by 11
So you dont need to hit enter. Just numbers.

**Comment by raguay** [comment]
I just overhauled the expose code for the Alfred Mjolnir workflow to give a list of every running application with one or more window. If an application that has only one open window is selected, then it simply brings it to the forefront. Otherwise, it will show all the windows for that application in a matrix and ask you for the column and row value (zero referenced). It will then put all the windows back to their original location and bring the one selected to the forefront.

Give it a try and let me know what you think. You can download the latest version from the aforementioned locations.

**Comment by KyleKing** [comment]
Thanks @raguay! I played around with the installation and got the expose working to show all windows and select one appropriately. I'm having trouble getting the update to work. It only shows:
![snap](http://snpy.link/XGXnjr)

**Comment by KyleKing** [comment]
On a side note, can Mjolnir hide a window? And not just minimize it?

**Comment by raguay** [comment]
mjolnir.application:hide()

The documentation in Dash show all of the functions.

**Comment by raguay** [comment]
Just updated the Mjolnir workflow in Alfred again. Two more modules have been pulled and a new command for just updating the init.lua file only and not installing modules:  mj:updateinit

**Comment by KyleKing** [comment]
Thanks for your quick answer and thanks for the consistent updates!
Btw, I just found a new way to keep up with updates through [Packal Updater](http://www.packal.org/workflow/packal-updater)
