### ISSUE TITLE
Question: Window Arranging

### ISSUE THREAD

**Issue by steveoh** [sdegutis/mjolnir#533]
I'm looking into migrating from slate since it basically doesn't work for me anymore. I used slate for arranging my applications. I never got to the point where I could have different arrangements based on the number of monitors but it looked like it could do that. I would take a snapshot and activate it to arrange my workspace. 

Is this something that mjolnir can do with the application, window, and grid plugins? Am I able to find open windows with mjolnir and move them to certain x,y coordinates and resize them to tetris up my monitors?

**Comment by cmsj** [comment]
@steveoh I'm not sure if it would work as-is in Mjolnir, but with probably little more than a quick port, https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/layout/init.lua would let you quickly apply a lot of layout decisions to your apps/windows. It supports multiple screens and because its data source is just a Lua table, you can manipulate it in code if you want (e.g. you could write something to walk all of the windows and snapshot them into such a table).
(I'm not dissing Mjomatic, it is an excellent module :)

**Comment by steveoh** [comment]
@cmsj, I like the idea of writing something to walk all of the open windows. slate did something similar to that. I've stopped using mjolnir since I haven't been able to arrange my desktop how I'd like. I will have to give that lua script a read and see how much I can understand and hopefully port.

**Comment by cmsj** [comment]
@steveoh out of interest, are you wanting to assign all the open things to static, pre-defined positions/sizes, or are you looking at something more dynamic, which simply figures out how many windows there are and makes them all fit somehow?
(I'm curious because the latter seems appealing, but I imagine it would be devilishly hard to avoid making windows be unhelpfully small, or making windows that are naturally portrait shaped, landscape sized!)

**Comment by steveoh** [comment]
cmsj, I'm more interested in the first. I want to have different setups for different monitor configurations that I run. I run 3 horizontal in the office, 2 vertical in the home office, and then 1 when remote. I'd like to arrange all of my things for these scenarios.

**Comment by cmsj** [comment]
@steveoh aha, then check out my config at https://github.com/Hammerspoon/hammerspoon/wiki/cmsj%27s-init.lua 

It has layouts for my two situations, and a screen watcher that applies the right one when the number of displays changes :)

**Comment by steveoh** [comment]
@cmsj should I be using hammerspoon then?

**Comment by cmsj** [comment]
Sorry, I just replied to the notification on my phone without checking which project this was in!

I don't want to use the Mjolnir project site as a recruitment ground. My apologies for being rude :/

**Comment by asmagill** [comment]
Just to put this out there -- there are very few actual changes to the core application code of Hammerspoon versus Mjolnir... most of the changes are in additional builtin modules, some of which are entirely in lua... I know that all of the modules I've written thus far (with perhaps some slight tweaking in names) will work in both.  I haven't looked at the specific modules Chris's code utilizes, but I'd bet it would take little more than some minor editing for it to work just as well in Mjolnir.

Even the modules which have a C library component will likely compile just fine for Mjolnir with the right makefile.

**Comment by steveoh** [comment]
please don't feel like you are being rude. I'd love to talk to you more in chat if you are able. I've tried a lot of window arrangement tools and am not afraid to try another one. I thought I read that mjolnir was the newest version of hammerspoon but i can't quite recall.
