### ISSUE TITLE
Menu item

### ISSUE THREAD

**Issue by keith** [sdegutis/mjolnir#56]
In v1.0b1 the menu item disappears on launch after you copy the default config.

**Comment by sdegutis** [comment]
@Keithbsmiley Hmm. I ran `mv ~/.hydra/init{,2}.lua` and relaunched Hydra v1.0b1, clicked 'Open Sample Config" from the menu, verified it's the same version of the file in this pre-release binary, copied the file contents, ran `pbpaste > ~/.hydra/init.lua`, and clicked "Reload Config" from the menu. I saw the alert "Error: attempt to call a table value" (presumably from `api.updates.check()` considering the same error happens when I click "Check for Update...") but the menu icon is still there for me.

**Comment by sdegutis** [comment]
Just fixed that other bug on master. Can't reproduce the bug you're seeing.
