### ISSUE TITLE
maximizing iTerm3 to fill the entire screen

### ISSUE THREAD

**Issue by FND** [sdegutis/mjolnir#562]
I use the following binding to maximize windows (without resorting to fullscreen):

```lua
local hotkey = require "mjolnir.hotkey"
local window = require "mjolnir.window"

hotkey.bind({"cmd", "alt", "ctrl"}, "up", function()
  local win = window.focusedwindow()
  local frame = win:frame()
  local screen = win:screen():fullframe()
  frame.x = 0
  frame.y = 0
  frame.w = screen.w
  frame.h = screen.h
  win:setframe(frame)
end)
```

Unfortunately, this never quite worked as expected: It leaves a small margin to the screen's bottom and/or right edge, which can be rather distracting.

This issue becomes even more pronounced with [iTerm3](https://iterm2.com/version3.html)'s borderless mode:

<img width="1440" alt="edges" src="https://cloud.githubusercontent.com/assets/3515/13195313/5649d080-d7af-11e5-81cc-4a12a03d2d97.png">
(That's another iTerm window in the lower right and a blank browser window beneath.)

Is there any way to work around this, actually filling the entire screen?

**Comment by sdegutis** [comment]
@FND Setting the height or width of a window via Mjolnir is literally the same as resizing the height or width using your mouse, and is subject to all the same limitations. Some windows "snap" their width and/or height to intervals while resizing. In this case, iTerm snaps to its character-based grid so that you never see half a character. That's not something we have any control over. It's outside Mjolnir's capabilities. However, you may be able to turn off that behavior from within iTerm. Check out their documentation. If it's not there, you can request them to add that feature, or add it yourself (iTerm is open source too).

**Comment by FND** [comment]
That makes sense, thanks for clarifying - I'll look into it.

**Comment by gnachman** [comment]
In 2.9+ (currently the beta version), you can turn on *Prefs > Advanced > Terminal windows resize smoothly* to turn off snap-to-grid and use all the space.

**Comment by FND** [comment]
Excellent, that works - thanks a lot @gnachman!

(FWIW, there's still a tiny margin at the bottom - visible as a blue bar in the OP's screenshot - but that seems to apply to all windows and isn't too distracting.)
