### ISSUE TITLE
REPL windows get lost

### ISSUE THREAD

**Issue by Habbie** [sdegutis/mjolnir#79]
Because the app is not in the dock, it's not in cmd-tab, and REPL windows that get obscured tend to get lost.

Suggestion for fixing: have a single REPL window that gets refocused (I presume this can be a sample.lua change)

**Comment by sdegutis** [comment]
@Habbie As long as the REPL is part of Hydra.app, and Hydra does not live in the Dock, the REPL window (or any textgrid) will not show up in Cmd-Tab, because Cmd-Tab only shows apps in the Dock. A simple work-around is to bind a hotkey in your config that runs `hydra.focushydra()`. But a more integrated solution is to offer an API to toggle whether Hydra is in the Dock or not. This would be useful while writing and testing our configs. And the API won't need Hydra to restart. So I've created issue #84 as the solution to this issue.
