### ISSUE TITLE
Execute Hydra commands from external process

### ISSUE THREAD

**Issue by Habbie** [sdegutis/mjolnir#91]
Allow sending of Lua snippets via some IPC mechanism. A command line tool (Applescript? dedicated binary?) that can send a Lua snippet in and get the output out would be enough. Building a REPL around that is easy then.

**Comment by sdegutis** [comment]
We'd have to write a command line tool that's dedicated to passing along its arguments and/or stdin to Hydra, which would then evaluate it and return the results back.

I'll have to re-read [this article about IPC on OSX](https://mikeash.com/pyblog/friday-qa-2009-01-16.html) to see what the best way to do this would be.

I've done this in the past using CocoaAsyncSocket (the GCD flavor, with the Unix sockets fork) but that felt very heavy-weight. There may be a simpler way that's not inefficient.

**Comment by sdegutis** [comment]
Probably going to just use `CFMessagePort` for this on both ends. The other command will be its own project (probably a new repo named `hydra-cli`) with a single executable named `hydra` as a very plain command-line utility and will thus be available via homebrew instead of cask. This utility will fire one-off messages to Hydra and then wait for its response, printing all of it to stdout, and then exiting. It will be ideal for executing named functions from other scripts, such as `hydra 'repl.open()'` and maybe `echo 'repl.open()' | hydra -`. Hydra.app will have a new function `hydra.startserver()` that makes it listen for messages from `hydra-cli` and answer them.

**Comment by sdegutis** [comment]
@Habbie no comprendo

**Comment by sdegutis** [comment]
@Habbie Oh so you just want to override the handler of the incoming message itself? So if you open it via `cli.listen()`, it would by default handle incoming messages using `cli.handlemsg`, but you could override `cli.handlemsg` yourself to be your own `function(str) -> str`. Sounds good.

**Comment by sdegutis** [comment]
:heart: :cake:

**Comment by sdegutis** [comment]
- Created https://github.com/sdegutis/hydra-cli

**Comment by sdegutis** [comment]
@Habbie btw sdegutis/hydra-cli#1

**Comment by sdegutis** [comment]
This is technically done, although the hydra-cli command isn't finished yet, so it's basically useless. Closing anyway.
